import React from 'react'
import { useNavigate } from 'react-router-dom'

function JoinSpace() {
  const navigate = useNavigate();
  const handleClick = () => {
    navigate('/launch')
  }
  return (
    <div className="App">
      <h1><a href="">Nomie</a></h1>

      <main>
        <h2>To join a space, enter your community-specific code</h2>

        <form className="codeInput">
          <input type="text">{/* to be generated by the next amazing team */}</input>
        </form>

        <div>
          <button className="btnBlack" onClick={handleClick}>Join Space</button>
        </div>

      </main>
    </div>
  )
}

export default JoinSpace