-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 14:57:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NomieDB
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `NomieDB` DEFAULT CHARACTER SET utf8 ;
USE `NomieDB` ;

-- -----------------------------------------------------
-- Table `NomieDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NomieDB`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  UNIQUE (`email`),
  PRIMARY KEY (`user_id`));

-- -----------------------------------------------------
-- Table `NomieDB`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NomieDB`.`profile` (
  `profile_id` INT AUTO_INCREMENT,
  `first_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `audio_url` VARCHAR(50) NULL,
  `image_url` VARCHAR(50) NULL,
  `pronoun` VARCHAR(16) NOT NULL,
  `profession` VARCHAR(32) NOT NULL,
  `hobby` VARCHAR(32) NOT NULL,
  `about` VARCHAR(255) NOT NULL,
  `activity` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`profile_id`));

-- -----------------------------------------------------
-- Table `NomieDB`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NomieDB`.`login` (
  `login_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`login_id`));

-- ------------------------------------------------------
-- Table `NomieDB`.`group`
-- ------------------------------------------------------
CREATE TABLE IF NOT EXISTS `NomieDB`.`group` (
  `group_id` VARCHAR(6),
  `group_name` VARCHAR(50),
  `space_affiliation` VARCHAR(255),
  PRIMARY KEY (`group_id`)
);

-- -------------------------------------------------------
-- Table `NomieDB`.`groupmembers`
-- -------------------------------------------------------
CREATE Table IF NOT EXISTS `NomieDB`.`groupmembers` (
  `group_id` VARCHAR(6),
  `member_id` INT AUTO_INCREMENT,
  `profile_id` INT,
  `leader` BOOL,
  PRIMARY KEY (`member_id`)
);

-- ---------------------------------------------------------
-- Join tables : groupmembers, group, and profile
-- use joined tables to populate Launch Page, Profile Onboard, Space Home, Member home
-- ----------------------------------------------------------
SELECT G.group_id, G.space_affiliation, M.member_id, P.profile_id, P.first_name, P.image_url, P.pronoun, M.leader
FROM (( NomieDB.groupmembers AS M
INNER JOIN NomieDB.group AS G ON M.group_id = G.group_id)
INNER JOIN NomieDB.profile AS P ON M.profile_id = P.profile_id);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
